%% BUILD_DSM_SIMULINK_MODEL
% Creates a Simulink model of the 4th-order CIFF DSM with Flash ADC
% and Thermometer DAC with optional DWA
%
% Usage: build_dsm_simulink_model(model_name, n_bits, V_fs, use_dwa)
%   model_name: Name for the new Simulink model
%   n_bits: ADC resolution (default: 5)
%   V_fs: Full scale voltage (default: 1.0)
%   use_dwa: Enable DWA (default: false)

function build_dsm_simulink_model(varargin)
    % Parse inputs
    if nargin >= 1
        model_name = varargin{1};
    else
        model_name = 'DSM_4th_Order_CIFF';
    end
    
    if nargin >= 2
        n_bits = varargin{2};
    else
        n_bits = 5;
    end
    
    if nargin >= 3
        V_fs = varargin{3};
    else
        V_fs = 1.0;
    end
    
    if nargin >= 4
        use_dwa = varargin{4};
    else
        use_dwa = false;
    end
    
    %% Design Parameters
    order = 4;
    OSR = 16;
    H_inf = 4.0;
    opt = 1;
    f0 = 0;
    
    % Sampling frequency
    fs = 2e6;
    
    %% Synthesize NTF and get coefficients
    addpath('dstoolbox');
    
    ntf = synthesizeNTF(order, OSR, opt, H_inf, f0);
    form = 'CIFF';
    [a, g, b, c] = realizeNTF(ntf, form);
    ABCD = stuffABCD(a, g, b, c, form);
    
    n_states = order;
    A_mat = ABCD(1:n_states, 1:n_states);
    B_mat = ABCD(1:n_states, n_states+1:end);
    C_mat = ABCD(n_states+1, 1:n_states);
    D_mat = ABCD(n_states+1, n_states+1:end);
    
    %% Create Simulink Model
    % Close existing model if open
    if bdIsLoaded(model_name)
        close_system(model_name, 0);
    end
    
    % Create new model
    new_system(model_name);
    open_system(model_name);
    
    % Set simulation parameters
    set_param(model_name, 'Solver', 'FixedStepDiscrete');
    set_param(model_name, 'FixedStep', '1/fs');
    set_param(model_name, 'StopTime', '0.01');
    
    % Add parameter definitions to model workspace
    set_param(model_name, 'PreLoadFcn', ...
        sprintf(['n_bits = %d;\n' ...
                 'V_fs = %.1f;\n' ...
                 'fs = %.0f;\n' ...
                 'n_levels = 2^n_bits;\n' ...
                 'n_comparators = n_levels - 1;\n' ...
                 'LSB = 2*V_fs / (n_levels - 1);\n' ...
                 'dither_std = LSB / 4;\n' ...
                 'use_dwa = %d;\n'], n_bits, V_fs, fs, use_dwa));
    
    %% Build the Model Blocks
    % Input sine wave
    add_block('simulink/Sources/Sine Wave', [model_name '/Input'], ...
        'Position', [30, 150, 60, 180], ...
        'Amplitude', '0.5', ...
        'Frequency', '2*pi*fs*sqrt(1/7)*8192/(2*16)/8192', ...
        'SampleTime', '1/fs');
    
    % Input port label
    add_block('simulink/Signal Routing/Goto', [model_name '/u'], ...
        'Position', [100, 150, 130, 180], ...
        'GotoTag', 'u', ...
        'ShowName', 'off');
    
    add_line(model_name, 'Input/1', 'u/1');
    
    % Feedback port
    add_block('simulink/Signal Routing/From', [model_name '/v_feedback'], ...
        'Position', [30, 250, 60, 280], ...
        'GotoTag', 'v', ...
        'ShowName', 'off');
    
    % Sum block for modulator input: y = C*x + D(1)*u + D(2)*v
    add_block('simulink/Math Operations/Sum', [model_name '/Mod_Sum'], ...
        'Position', [200, 200, 230, 250], ...
        'Inputs', '+++', ...
        'IconShape', 'round');
    
    % Input gain (D(1) = 1 for CIFF)
    add_block('simulink/Signal Routing/From', [model_name '/From_u'], ...
        'Position', [150, 160, 180, 190], ...
        'GotoTag', 'u');
    
    % Feedback gain D(2)
    add_block('simulink/Math Operations/Gain', [model_name '/Gain_D2'], ...
        'Position', [100, 250, 130, 280], ...
        'Gain', mat2str(D_mat(2)));
    
    add_line(model_name, 'From_u/1', 'Mod_Sum/1');
    add_line(model_name, 'v_feedback/1', 'Gain_D2/1');
    add_line(model_name, 'Gain_D2/1', 'Mod_Sum/2');
    
    % State integrators
    x_positions = [400, 550, 700, 850];
    y_pos = 200;
    
    for i = 1:n_states
        % Discrete-time integrator for each state
        add_block('simulink/Discrete/Discrete-Time Integrator', ...
            [model_name sprintf('/Integrator_%d', i)], ...
            'Position', [x_positions(i), y_pos, x_positions(i)+40, y_pos+40], ...
            'GainValue', '1', ...
            'SampleTime', '1/fs', ...
            'ShowName', 'off');
        
        % State feedback gain (from C matrix)
        if i <= length(C_mat)
            gain_val = C_mat(i);
        else
            gain_val = 0;
        end
        
        add_block('simulink/Math Operations/Gain', ...
            [model_name sprintf('/Gain_C%d', i)], ...
            'Position', [x_positions(i)-50, y_pos, x_positions(i)-20, y_pos+40], ...
            'Gain', num2str(gain_val), ...
            'ShowName', 'off');
        
        % Connect state to modulator sum through gain
        if i == 1
            add_line(model_name, sprintf('Integrator_%d/1', i), ...
                sprintf('Gain_C%d/1', i));
            add_line(model_name, sprintf('Gain_C%d/1', i), 'Mod_Sum/3');
        end
        
        % A matrix connections (state feedback)
        if i < n_states
            % Connect integrator i to integrator i+1
            for j = i+1:n_states
                if A_mat(j,i) ~= 0
                    add_block('simulink/Math Operations/Gain', ...
                        [model_name sprintf('/Gain_A%d%d', j, i)], ...
                        'Position', [x_positions(i), y_pos + 60*(j-i), x_positions(i)+40, y_pos + 60*(j-i) + 40], ...
                        'Gain', num2str(A_mat(j,i)), ...
                        'ShowName', 'off');
                    add_line(model_name, sprintf('Integrator_%d/1', i), ...
                        sprintf('Gain_A%d%d/1', j, i));
                end
            end
        end
        
        % Resonator feedback (g coefficients)
        if i <= length(g) && g(i) ~= 0 && i < n_states
            add_block('simulink/Math Operations/Gain', ...
                [model_name sprintf('/Gain_g%d', i)], ...
                'Position', [x_positions(i+1)-30, y_pos-80, x_positions(i+1), y_pos-50], ...
                'Gain', num2str(-g(i)), ...
                'ShowName', 'off');
            add_line(model_name, sprintf('Integrator_%d/1', i), ...
                sprintf('Gain_g%d/1', i));
        end
        
        % B matrix input connections
        add_block('simulink/Signal Routing/From', ...
            [model_name sprintf('/From_u_%d', i)], ...
            'Position', [x_positions(i)-100, y_pos-30, x_positions(i)-70, y_pos], ...
            'GotoTag', 'u', ...
            'ShowName', 'off');
        
        if B_mat(i,1) ~= 0
            add_block('simulink/Math Operations/Gain', ...
                [model_name sprintf('/Gain_Bu%d', i)], ...
                'Position', [x_positions(i)-80, y_pos-30, x_positions(i)-50, y_pos], ...
                'Gain', num2str(B_mat(i,1)), ...
                'ShowName', 'off');
            add_line(model_name, sprintf('From_u_%d/1', i), ...
                sprintf('Gain_Bu%d/1', i));
            add_line(model_name, sprintf('Gain_Bu%d/1', i), ...
                sprintf('Integrator_%d/1', i));
        end
        
        % Feedback input to integrator
        add_block('simulink/Signal Routing/From', ...
            [model_name sprintf('/From_v_%d', i)], ...
            'Position', [x_positions(i)-100, y_pos+60, x_positions(i)-70, y_pos+90], ...
            'GotoTag', 'v', ...
            'ShowName', 'off');
        
        if B_mat(i,2) ~= 0
            add_block('simulink/Math Operations/Gain', ...
                [model_name sprintf('/Gain_Bv%d', i)], ...
                'Position', [x_positions(i)-80, y_pos+60, x_positions(i)-50, y_pos+90], ...
                'Gain', num2str(B_mat(i,2)), ...
                'ShowName', 'off');
            add_line(model_name, sprintf('From_v_%d/1', i), ...
                sprintf('Gain_Bv%d/1', i));
            add_line(model_name, sprintf('Gain_Bv%d/1', i), ...
                sprintf('Integrator_%d/1', i));
        end
    end
    
    %% Flash ADC with Dither
    % Dither generation
    add_block('simulink/Sources/Random Number', [model_name '/Dither'], ...
        'Position', [200, 350, 230, 380], ...
        'Distribution', 'Gaussian', ...
        'Mean', '0', ...
        'Variance', '(LSB/4)^2', ...
        'SampleTime', '1/fs');
    
    % Sum for dither addition
    add_block('simulink/Math Operations/Sum', [model_name '/Add_Dither'], ...
        'Position', [300, 300, 330, 330], ...
        'Inputs', '++');
    
    add_line(model_name, 'Mod_Sum/1', 'Add_Dither/1');
    add_line(model_name, 'Dither/1', 'Add_Dither/2');
    
    % MATLAB Function block for Flash ADC
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
        [model_name '/Flash_ADC'], ...
        'Position', [400, 300, 500, 350], ...
        'MATLABFcn', sprintf([...
            'function binary = fcn(y, V_fs, n_bits)\n' ...
            '    n_levels = 2^n_bits;\n' ...
            '    n_comparators = n_levels - 1;\n' ...
            '    v_min = -V_fs;\n' ...
            '    v_max = V_fs;\n' ...
            '    lsb = (v_max - v_min) / (n_levels - 1);\n' ...
            '    thresholds = v_min + lsb/2 : lsb : v_max - lsb/2;\n' ...
            '    v_in_clipped = max(v_min, min(v_max, y));\n' ...
            '    thermometer = v_in_clipped > thresholds;\n' ...
            '    level_idx = sum(thermometer);\n' ...
            '    output_levels = linspace(v_min, v_max, n_levels);\n' ...
            '    binary = output_levels(level_idx + 1);\n' ...
            'end']));
    
    add_line(model_name, 'Add_Dither/1', 'Flash_ADC/1');
    
    %% DAC with mismatch and DWA
    if use_dwa
        dac_name = 'Thermometer_DAC_DWA';
        dac_code = sprintf([...
            'function v_dac = fcn(binary, V_fs, n_bits, use_dwa)\n' ...
            '    persistent dwa_start bit_weights;\n' ...
            '    if isempty(dwa_start), dwa_start = 1; end\n' ...
            '    if isempty(bit_weights)\n' ...
            '        n_comparators = 2^n_bits - 1;\n' ...
            '        nominal = 2*V_fs/n_comparators;\n' ...
            '        rng(42); bit_weights = nominal*(1+0.005*randn(1,n_comparators));\n' ...
            '    end\n' ...
            '    n_levels = 2^n_bits;\n' ...
            '    n_comparators = n_levels - 1;\n' ...
            '    v_min = -V_fs; v_max = V_fs;\n' ...
            '    lsb = (v_max-v_min)/(n_levels-1);\n' ...
            '    thresholds = v_min+lsb/2:lsb:v_max-lsb/2;\n' ...
            '    level = round((binary - v_min)/lsb);\n' ...
            '    k = max(0, min(n_comparators, level));\n' ...
            '    dwa_therm = zeros(1, n_comparators);\n' ...
            '    for j=0:k-1\n' ...
            '        idx = mod(dwa_start-1+j, n_comparators) + 1;\n' ...
            '        dwa_therm(idx) = 1;\n' ...
            '    end\n' ...
            '    contribution = 0;\n' ...
            '    for j=1:n_comparators\n' ...
            '        if dwa_therm(j), contribution = contribution + bit_weights(j);\n' ...
            '        else, contribution = contribution - bit_weights(j); end\n' ...
            '    end\n' ...
            '    v_dac = contribution * 0.5;\n' ...
            '    if k > 0 && k < n_comparators\n' ...
            '        dwa_start = mod(dwa_start-1+k, n_comparators) + 1;\n' ...
            '    end\n' ...
            'end']);
    else
        dac_name = 'Thermometer_DAC';
        dac_code = sprintf([...
            'function v_dac = fcn(binary, V_fs, n_bits)\n' ...
            '    persistent bit_weights;\n' ...
            '    if isempty(bit_weights)\n' ...
            '        n_comparators = 2^n_bits - 1;\n' ...
            '        nominal = 2*V_fs/n_comparators;\n' ...
            '        rng(42); bit_weights = nominal*(1+0.005*randn(1,n_comparators));\n' ...
            '    end\n' ...
            '    n_levels = 2^n_bits;\n' ...
            '    n_comparators = n_levels - 1;\n' ...
            '    v_min = -V_fs; v_max = V_fs;\n' ...
            '    lsb = (v_max-v_min)/(n_levels-1);\n' ...
            '    thresholds = v_min+lsb/2:lsb:v_max-lsb/2;\n' ...
            '    v_in = binary;\n' ...
            '    therm = v_in > thresholds;\n' ...
            '    contribution = 0;\n' ...
            '    for j=1:n_comparators\n' ...
            '        if therm(j), contribution = contribution + bit_weights(j);\n' ...
            '        else, contribution = contribution - bit_weights(j); end\n' ...
            '    end\n' ...
            '    v_dac = contribution * 0.5;\n' ...
            'end']);
    end
    
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
        [model_name '/' dac_name], ...
        'Position', [600, 300, 700, 350], ...
        'MATLABFcn', dac_code);
    
    add_line(model_name, 'Flash_ADC/1', [dac_name '/1']);
    
    % Output the DAC signal as feedback
    add_block('simulink/Signal Routing/Goto', [model_name '/v_output'], ...
        'Position', [800, 310, 830, 340], ...
        'GotoTag', 'v', ...
        'ShowName', 'off');
    
    add_line(model_name, [dac_name '/1'], 'v_output/1');
    
    %% ADC Output Scope
    add_block('simulink/Sinks/Scope', [model_name '/ADC_Output'], ...
        'Position', [750, 250, 800, 290], ...
        'NumInputPorts', '2');
    
    add_line(model_name, 'Flash_ADC/1', 'ADC_Output/1');
    add_block('simulink/Signal Routing/From', [model_name '/From_u_scope'], ...
        'Position', [700, 260, 730, 290], ...
        'GotoTag', 'u');
    add_line(model_name, 'From_u_scope/1', 'ADC_Output/2');
    
    %% Arrange the layout
    set_param(model_name, 'ZoomFactor', 'Fit');
    
    fprintf('Simulink model "%s" created successfully!\n', model_name);
    fprintf('  Configuration: %d-bit Flash ADC, V_fs = %.1fV\n', n_bits, V_fs);
    if use_dwa
        fprintf('  DWA: ENABLED\n');
    else
        fprintf('  DWA: Disabled (static mismatch)\n');
    end
    fprintf('  Run the model to simulate the DSM.\n');
end