%% test_build_3rd_order_simulink_model.m
% Build and smoke-test a Simulink model for the 3rd-order CIFF DSM example.

clearvars; close all; clc;

addpath(fullfile(fileparts(mfilename('fullpath')), 'dstoolbox'));

order = 3;
OSR = 32;
H_inf = 4.0;
opt = 1;
f0 = 0;
form = 'CIFF';
fs = 10e6;
n_bits = 4;
V_fs = 1.0;

ntf = synthesizeNTF(order, OSR, opt, H_inf, f0);
[a, g, b, c] = realizeNTF(ntf, form);

[model_name, model_path, info] = build_dsm_simulink_model( ...
    'model_name', 'dsm_3rd_order_ciff_10mhz_topology_model', ...
    'output_dir', fileparts(mfilename('fullpath')), ...
    'a', a, ...
    'g', g, ...
    'b', b, ...
    'c', c, ...
    'form', form, ...
    'fs', fs, ...
    'OSR', OSR, ...
    'n_bits', n_bits, ...
    'V_fs', V_fs, ...
    'input_amplitude', 0.5, ...
    'stop_time', 2e-4, ...
    'implementation', 'expanded', ...
    'open_model', false);

disp(model_name);
disp(model_path);
disp(info.form);
disp(info.implementation);
disp(info.ABCD);
