%% BUILD_MASH_21_DSM_SIMULINK_MODEL
% Compatibility wrapper around the generic MASH Simulink builder for the
% specific 2-1 case used by the current reference flow.

function [model_name, model_path, info] = build_mash_21_dsm_simulink_model(varargin)
    spec = parse_inputs(varargin{:});

    stages = [ ...
        struct( ...
            'name', 'Stage1', ...
            'ntf', spec.stage1_ntf, ...
            'ABCD', spec.stage1_abcd, ...
            'form', spec.stage1_form, ...
            'order', spec.stage1_order, ...
            'opt', spec.stage1_opt, ...
            'H_inf', spec.stage1_H_inf, ...
            'n_bits', spec.n_bits_stage1, ...
            'n_levels', spec.n_levels_stage1, ...
            'source', 'external'), ...
        struct( ...
            'name', 'Stage2', ...
            'ntf', spec.stage2_ntf, ...
            'ABCD', spec.stage2_abcd, ...
            'form', spec.stage2_form, ...
            'order', spec.stage2_order, ...
            'opt', spec.stage2_opt, ...
            'H_inf', spec.stage2_H_inf, ...
            'n_bits', spec.n_bits_stage2, ...
            'n_levels', spec.n_levels_stage2, ...
            'source', 'residue1')];

    [model_name, model_path, info] = build_mash_dsm_simulink_model( ...
        'model_name', spec.model_name, ...
        'output_dir', spec.output_dir, ...
        'stages', stages, ...
        'fs', spec.fs, ...
        'OSR', spec.OSR, ...
        'V_fs', spec.V_fs, ...
        'input_amplitude', spec.input_amplitude, ...
        'input_frequency', spec.input_frequency, ...
        'stop_time', spec.stop_time, ...
        'open_model', spec.open_model);

    info.stage1 = info.stages(1);
    info.stage2 = info.stages(2);
    info.cancel_num = info.combiner_filters{2}.num;
    info.cancel_den = info.combiner_filters{2}.den;
end

function spec = parse_inputs(varargin)
defaults = struct( ...
    'model_name', 'dsm_mash_2_1_ciff_10mhz_topology_model', ...
    'output_dir', pwd, ...
    'stage1_ntf', [], ...
    'stage2_ntf', [], ...
    'stage1_abcd', [], ...
    'stage2_abcd', [], ...
    'stage1_form', 'CIFF', ...
    'stage2_form', 'CIFF', ...
    'fs', [], ...
    'OSR', 32, ...
    'stage1_order', 2, ...
    'stage2_order', 1, ...
    'stage1_opt', 0, ...
    'stage2_opt', 0, ...
    'stage1_H_inf', 2.0, ...
    'stage2_H_inf', 1.5, ...
    'n_bits_stage1', 4, ...
    'n_bits_stage2', 4, ...
    'n_levels_stage1', [], ...
    'n_levels_stage2', [], ...
    'V_fs', 1.0, ...
    'input_amplitude', 0.5, ...
    'input_frequency', [], ...
    'stop_time', [], ...
    'open_model', false);

if nargin == 1 && isstruct(varargin{1})
    spec = defaults;
    user = varargin{1};
    names = fieldnames(user);
    for i = 1:numel(names)
        spec.(names{i}) = user.(names{i});
    end
    return;
end

p = inputParser;
fields = fieldnames(defaults);
for i = 1:numel(fields)
    addParameter(p, fields{i}, defaults.(fields{i}));
end
parse(p, varargin{:});
spec = p.Results;
end
