%% test_build_mash_2_1_simulink_model.m
% Build and smoke-test the 2-1 MASH DT Simulink model.

clearvars; close all; clc;

script_dir = fileparts(mfilename('fullpath'));
addpath(fullfile(fileparts(fileparts(script_dir)), 'common'));
refs_root = setup_references_paths();

[model_name, model_path, info] = build_mash_dsm_simulink_model( ...
    'model_name', 'dsm_mash_2_1_ciff_10mhz_topology_model', ...
    'output_dir', fullfile(refs_root, 'results', 'simulink', 'dt'), ...
    'stages', [ ...
        struct('name', 'Stage1', 'order', 2, 'opt', 0, 'H_inf', 2.0, 'form', 'CIFF', 'n_bits', 4, 'source', 'external'), ...
        struct('name', 'Stage2', 'order', 1, 'opt', 0, 'H_inf', 1.5, 'form', 'CIFF', 'n_bits', 4, 'source', 'residue1')], ...
    'fs', 10e6, ...
    'OSR', 32, ...
    'V_fs', 1.0, ...
    'input_amplitude', 0.5, ...
    'stop_time', 2e-4, ...
    'open_model', false);

disp(model_name);
disp(model_path);
disp(info.stages(1).form);
disp(info.stages(2).form);
disp(info.combiner_filters{2}.num);
disp(info.combiner_filters{2}.den);
